name: Parallel Jobs with Success

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Simular un fallo
        run: exit 1
    continue-on-error: true  # Ignora el fallo para que no afecte directamente al resultado global

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Simular éxito
        run: echo "Este job ha ido bien"

  final_status:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: always()  # Asegura que este job se ejecute siempre, incluso si algún job falló
    steps:
      - name: Verificar estado de los jobs
        run: |
          echo "Job1: ${{ needs.job1.result }}"
          echo "Job2: ${{ needs.job2.result }}"

      - name: Forzar éxito si al menos uno fue exitoso
        if: success() || failure()  # Se ejecuta siempre y no bloquea el workflow
        run: exit 0  # Siempre finaliza correctamente
