name: Conditional Workflow Status

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Simular éxito en job1
        run: echo "Job 1 completado correctamente"

  job2:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [job1]  # Solo se ejecuta si job1 finaliza correctamente
    steps:
      - name: Simular fallo en job2
        run: exit 1

  job3:
    runs-on: ubuntu-latest
    needs: [job1]  # Solo se ejecuta si job1 finaliza correctamente
    steps:
      - name: Simular éxito en job3
        run: echo "Job 3 completado correctamente"
